### ISSUE TITLE
Can't change input

### ISSUE THREAD

**Issue by Stesus** [exiva/Vizio_SmartCast_API#12]
I can't get the tv to change inputs. I can send key pressed, but every time i try to change the input I get a HASHVAL_ERROR. I noticed the HASHVAL given for the current input isn't listed when I list all inputs. Has anyone has this problem?

**Comment by Stesus** [comment]
I've noticed that the HASHVAL given at current_input doesn't show up on name_input.

**Comment by sevvy325** [comment]
The issue is the HASHVAL passed should be that of the current input, not that of the desired input.

**Comment by Stesus** [comment]
Thanks a lot, I have it working now.
