### ISSUE TITLE
New firmware update

### ISSUE THREAD

**Issue by rmurdoch328** [exiva/Vizio_SmartCast_API#15]
Hello,
I have a Vizio E70U-D3 tv that I was able to communicate with using the GET and PUT urls. On March 21, 2018 my TV get a firmware update and now I am getting and SSL error unable to open channel. It appears that this update removed an open SSL cert. 
Do you have any ideas on how to get around this?
Thanks.

**Comment by roligtroll** [comment]
Which firmware version do you have after the update?

**Comment by rmurdoch328** [comment]
It is on version 4.0.23.2 now

**Comment by ShaunInIdaho** [comment]
I am also having this issue as of today.  4 of 5 of my TVs have updated and now I'm having issues creating the ssl/tls secure channel

**Comment by grouma** [comment]
+1 Same issue here.

**Comment by willsy7** [comment]
Another with the same issue and version as ShaunInIdaho pointed out.

**Comment by rjbouch** [comment]
Using port 7345 seems to resolve the issue.

**Comment by ShaunInIdaho** [comment]
Confirmed, 7345 works.  I was actually running a port scan overnight last night just to check :)

**Comment by rmurdoch328** [comment]
The same port works for me as well. Thank you!

**Comment by t1mlopez** [comment]
7345 works for me too! Thanks!

**Comment by rmurdoch328** [comment]
I am able to connect using the 7345 port, I'm just having an issue pairing. I can sent the pairing/start request, the pin shows on the TV, but when I send the pairing/pair request I get a CHALLENGE_INCORRECT response. Any suggestions?

**Comment by exiva** [comment]
Updated documentation in https://github.com/exiva/Vizio_SmartCast_API/commit/b18204d9acab1111748d6bcede8bb11d5f55b570

**Comment by exiva** [comment]
I also love that you called Vizio for it @ShaunInIdaho 😂
