### ISSUE TITLE
Can't change input using /menu_native/dynamic/tv_settings/devices/current_input

### ISSUE THREAD

**Issue by samsp99** [exiva/Vizio_SmartCast_API#22]
I am trying to change the input using:
curl -k -H "Content-Type: application/json" -H "AUTH:Zz0gpzfgrm" -X PUT -d '{"REQUEST": "MODIFY","VALUE": "HDMI-1","HASHVAL": 2145620233}' https://192.168.1.237:7345/menu_native/dynamic/tv_settings/devices/current_input

using the name and hash values from https://192.168.1.237:7345/menu_native/dynamic/tv_settings/devices/name_input, but each time I get a hash value error:

{"STATUS": {"RESULT": "HASHVAL_ERROR", "DETAIL": "Hashval error"},

What am I doing wrong?

**Comment by exiva** [comment]
You need to use the latest hashval from each request. Docs were updated to reflect this. Older vizio sets didn't verify this, newer ones do.
