### ISSUE TITLE
Determining the parameters needed to launch an app

### ISSUE THREAD

**Issue by raman325** [exiva/Vizio_SmartCast_API#25]
Hi, I was looking through the SmartCast APK source code to try to address vkorn/pyvizio#105 and I discovered that the app queries the following endpoints to get the latest version of the files mentioned here: https://github.com/exiva/Vizio_SmartCast_API#app-ids

http://hometest.buddytv.netdna-cdn.com/appservice/vizio_apps_prod.json
http://hometest.buddytv.netdna-cdn.com/appservice/app_availability_prod.json

It looks like those two files can be used to obtain the latest list of apps mapped to their `NAME_SPACE`, `APP_ID`, and `MESSAGE`. Progress!

**Comment by michaelmaston** [comment]
Great stuff. Between these two files you can determine the namespace, appid and message to launch each supported app as well as some special cases on some models that use different values than most.  And also metadata about where various apps are supported (US, Canada, Mexico or globally it appears) so you can only include the apps that your TV (in theory) supports based on the country.  For example, some apps are only marked for the US. 

I've already integrated this stuff into my code to add new apps over time.

Thanks for the contribution man.  I know it was a year ago but still very helpful.

**Comment by exiva** [comment]
Thanks for posting, added this to the documentation

**Comment by kbrown01** [comment]
And that file is now gone so it all is broken back to the built in sources. Please tell me that someone downloaded a copy of the latest JSON!

**Comment by raman325** [comment]
I believe these are the new locations for this data:
http://scfs.vizio.com/appservice/vizio_apps_prod.json
http://scfs.vizio.com/appservice/app_availability_prod.json
