### ISSUE TITLE
Pairing Issues

### ISSUE THREAD

**Issue by chom1991** [exiva/Vizio_SmartCast_API#26]
Having issues while pairing a 2019 P Series. OS is 6+

When I enter in said pairing command, I run into an error.
curl -k -H "Content-Type: application/json" -X PUT -d '{"DEVICE_ID":"73777","DEVICE_NAME":"IP Control"}' https://10.0.10.198:7345/pairing/start
{"STATUS": "JSON parse error - No JSON object could be decoded"}

Running this on windows with node.js and installed the python and npm dependencies listed onsite. 

Running on mac os, I was able to pair and use the get commands however, the put commands don't appear to be doing anything. Could I be missing additional dependencies on this machine as well?

**Comment by exiva** [comment]
Windows might be mangling the json passed in the cli, but just a guess.

You should get a response back on the put commands when the JSON is valid, if it's invalid it returns nothing. So I'd check the json is valid.
