### ISSUE TITLE
TV Power State

### ISSUE THREAD

**Issue by cbulock** [exiva/Vizio_SmartCast_API#3]
I hope I'm just missing something in the docs, but is there a way to determine what the current power state of the TV is?

**Comment by exiva** [comment]
The closest you can get is `/state/device/power_mode` the native SmartCast app hits this endpoint every second to see if the set is on. There's nothing really useful returned in it though.

**Comment by cbulock** [comment]
That works perfect, thank you!

**Comment by exiva** [comment]
No problem, I'll add this into the docs.
