### ISSUE TITLE
Not an issue but didnt know where else to post

### ISSUE THREAD

**Issue by andypm1982** [exiva/Vizio_SmartCast_API#32]
hi there.

can you provide any documentation on how to use this in home assistant??

ive spent what seems like hours trying to find some useful documentation on how to make this work with no luck apart from this post.

I have a vizio smart tv i would like to intergrate.

Thanks.

**Comment by exiva** [comment]
You'd have to write a plugin. This is just docs for the TV's API server. Looks like there's a plugin @ https://www.home-assistant.io/integrations/vizio/

**Comment by andypm1982** [comment]
Yes I sort of understand that part. But even after the plug-in installed there is no further documentation on how to configure simple remote commands.

Also on another post I found information that pointed to this plugin no longer being needed as it is now embedded into the OS. I didn’t need to do anything other than tick a box or 2 to get power and volume commands working. Why are simple navigation keys so much more work?


Sent from my iPhone

On 1 Jan 2022, at 23:18, Travis La Marr ***@***.***> wrote:

﻿

Closed #32<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fexiva%2FVizio_SmartCast_API%2Fissues%2F32&data=04%7C01%7C%7Cef2b5ed6466a40486b7f08d9cdaf5f7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637766975363611851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f%2Buw01%2BQ82aBmo8w9Z9yYZU2noWBjbi5ymzyHaUOx8A%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fexiva%2FVizio_SmartCast_API%2Fissues%2F32%23event-5832321380&data=04%7C01%7C%7Cef2b5ed6466a40486b7f08d9cdaf5f7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637766975363621806%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QSSM%2FFaaa8WALDZ%2Bl7jqmGz0iZDQAOoOwAQo7mRKS%2BE%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW4UW5RXHPW3BK5NEDKSWSTUT7N35ANCNFSM5KXADXGA&data=04%7C01%7C%7Cef2b5ed6466a40486b7f08d9cdaf5f7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637766975363631763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Vq4JWAkBmfBQopDGQPizDjM5GezkwZazb0Vgq%2FMEqEk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cef2b5ed6466a40486b7f08d9cdaf5f7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637766975363641718%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R3l2PZDJVTW%2BvJCu6l6W%2BmIa%2FGCpNWf%2BJF7C%2FYbYxVI%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cef2b5ed6466a40486b7f08d9cdaf5f7f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637766975363651675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wtboNU57GDimxhzhtMPCSQD3nvnU2aACPENtNXKQ2rA%3D&reserved=0>.
